version: '3'
services:
  database:
    image: postgres
    container_name: postgres-db
    environment:
      - 'POSTGRES_PASSWORD=1425'
      - 'POSTGRES_DB=postgres'
    ports:
        - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

networks:
  backend: