version: '3'
services:
  db:
    image: keinos/sqlite3:latest
    container_name: mysql.db
    environment:
      - SQLITE_DATABASE=database.sqlite
    volumes:
      - ./data:/data
    restart: always
    networks:
      - backend

networks:
  backend: